### ISSUE TITLE
Hovertext displays too far down in window (minor)

### ISSUE THREAD

**Issue by CelticWraith** [IdleLands/WebFE#56] opened 2015-01-06 17:17 UTC
Areas affected: Vitals window, Inventory page, Pet Vitals window

Hovering your mouse over the various icons for strength, wisdom, etc. displays what the icon represents too far down in the window, causing a scroll bar to appear with the information hidden just off-window.

The top rows in each window are the only that work correctly.

**Comment by seiyria** [comment] 2015-01-06 17:35
duplicate of #49

**Closed by seiyria** 2015-01-06 17:35 UTC
